name: ci
on:
    push:
        branches:
            workflows
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Generate build files
              run: cmake -B build
            - name: Build
              run: cmake --build